### ISSUE TITLE
All component's html show in a page

### ISSUE THREAD

**Issue by longhoang2984** [Ismaestro/angular4-example-app#13]
Hello everyone,

I just add `{{abc.xyz}}` in hero-list.component.html. And the page show:
<img width="1280" alt="screen shot 2017-09-11 at 19 08 21" src="https://user-images.githubusercontent.com/11419002/30273837-e1600960-9724-11e7-827b-a090876db88d.png">

How can I do to fixed it without delete `{{abc.xyz}}` . Because in the future, I can't sure I don't have error somewhere in html.

**Comment by Ismaestro** [comment]
Hi @longhoang2984,

Sorry but I don't understand. If you add `{{abc.xyz}}` to any page, it should fail and broke the page render (because abc is not defined). And looking to that screenshot, it seems like you added top-hero component to the hero-list component.

Are you sure about that? Can you provide your hero-list.component.html code? Maybe you can deploy to your github pages so we can see the problem.

BR

**Comment by longhoang2984** [comment]
Hi @Ismaestro ,

I just download your source code, and try to add something with error : 'not defined'. My project have the same problem. I can't request my teammates 'Zero bug'

**Comment by Ismaestro** [comment]
[This](https://stackoverflow.com/questions/34910928/angular2-error-if-dont-check-if-object-field-exists), maybe helps.

**Comment by longhoang2984** [comment]
remove BrowserAnimationsModule to resolved this problem. Tks @Ismaestro
