### ISSUE TITLE
sidebar with submenu and profile details

### ISSUE THREAD

**Issue by dhanarajp** [Ismaestro/angular4-example-app#14]
Hi Team,

Really very helpful your code, can you help please how to create in sidebar with sub menu and profile details as like material design theme .
And is there any grid system for material design like bootstrap have col-sm-1 to 12. I tried to understand the grid and structure in material but unable to create proper structure please suggest the webside how to develop the project and best practice structure.

**Comment by Ismaestro** [comment]
Hi @dhanarajp,

Do you mean [this](https://material.angular.io/components/sidenav/overview)?

For the grid system we are currently working to add [flex-layout](https://github.com/angular/flex-layout). You will see it in a few days.

BR

**Comment by dhanarajp** [comment]
Hi Ismaestro,

Thank you so much for gave me a reference link and docs, 
can you suggest how to create side nav bar with sub menus?? i using currently below code for submenu, using "**Expansion Panel**", i dont know whether is correct way or not.

## <mat-expansion-panel-header>
    <mat-panel-title>
      Personal data
    </mat-panel-title>
    <mat-panel-description>
      Type your name and age
    </mat-panel-description>
  </mat-expansion-panel-header>

**Comment by Ismaestro** [comment]
First, related to the grid system, there is a new version with flex layout available. You can see it in nav, footer and hero-top components templates It's very similar to bootstrap system, and I've made some examples in order to see it in action with responsive, specially in mobile.

Regarding to the sub menus, what do you mean specifically? [this](https://www.google.es/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiDmZP3tv3WAhUHzxQKHaZVDqAQjRwIBw&url=https%3A%2F%2Fwww.templatemonster.com%2Fblog%2Fcolor-coded-dropdown-navigation-with-submenus%2F&psig=AOvVaw27iMasRAU1I1cII7B82974&ust=1508528017910381)?

In that case you have [mat-menu](https://material.angular.io/components/menu/overview) which is used in the project to show the list of languages available.

In other case, please tell me with more details what do you want.

BR

**Comment by dhanarajp** [comment]
@Ismaestro thanks for your reply and guide to me. i achieved menu with submenu once again thanks 

![image](https://user-images.githubusercontent.com/22543749/31861005-e2982096-b741-11e7-9fa8-0309f89929cb.png)
